<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Web Development Resources</title>

        <link href=<?php echo BASE_URL . "/css/bootstrap.min.css"; ?> rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href=<?php echo BASE_URL . "/css/style.css"; ?>>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src=<?php echo BASE_URL . "/js/bootstrap.min.js"; ?>></script>
        <script src=<?php echo BASE_URL . "/js/app.js"; ?>></script>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href=<?php echo BASE_URL . "/index.php"; ?>>Web Development Resources</a>
                </div>
                <a href=<?php echo BASE_URL . '/new/'; ?> type="button" class="btn btn-default navbar-btn navbar-right">New Website</a>
            </div>

        </nav>

        <div class="container">

        <!--      Specific page content goes here      -->
            <?php $this->content(); ?>

        </div>

        <nav class="navbar navbar-default navbar-inverse navbar-fixed-bottom" role="navigation">
            <div class="container-fluid">
                <div class="navbar-footer">
                    <p class="copyright">&copy 2015 Korey McMurtrey</p>
                </div>
            </div>

        </nav>

    </body>
</html>