<?php

//Assign $websites and $categories data to $this-> so the template can access it.
$websites = $this->websites;
$categories = $this->categories;
$p = $this->p;
?>

<h1><a href="index.php">Web Development Resources</a></h1>
<div class="row">
    <div class="website-list col-md-6 col-md-offset-1">
        <ol>
            <!-- loop through each website -->
            <?php foreach( $websites as $website ) : ?>
                <li>
                    <!-- output: <a href="__URL__">__TITLE__</a> -->
                    <a href="<?php echo $website['url'] ?>" class="website-title"><?php echo $website['title'] ?></a>
                    <p>Description: <?php echo $website['description'] ?></p>
                    <a href="edit.php?id=<?php echo $website['id'] ?>" class="btn btn-primary btn-xs" role="button">Edit</a>
                    <a class="btn btn-default btn-xs delete-btn" role="button" data-toggle="modal" data-target="#confirm-delete" data-href="delete.php?id=<?php echo $website['id']; ?>">Delete</a>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>

    <div class="sidebar col-md-3 col-md-offset-1">
        <h2>Category</h2>

        <ol>
            <?php foreach ( $categories as $category ) : ?>
                <li>
                    <a href="<?php echo 'index.php?category=' . $category['category']; ?>"><?php echo $category['category']; ?></a>
                </li>
            <?php endforeach; ?>
        </ol>

    </div>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <ul class="pagination">
            <?php for ($i = 1; $i <= $p->totalPages; $i++) { ?>
                <?php echo '<li>' . $i . '</li>'; ?>
            <?php }; ?>
        </ul>
    </div>
</div>